### ISSUE TITLE
Schema for manifest validation is out of date

### ISSUE THREAD

**Issue by cjonesdoordash** [webextension-toolbox/webpack-webextension-plugin#357]
The current JSON schema used for manifest validation only includes `not-allowed` and `spanning` for the `incognito` property where as the current v3 schema supports all of the following: https://developer.chrome.com/docs/extensions/mv3/manifest/incognito.

This causes builds to fail that don't skip manifest validation.

**Comment by tm1000** [comment]
Hi there

The schema is generated from the types at definitely typed. This will need to be added there: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chrome

**Comment by here-nerd** [comment]
> Hi there
> 
> The schema is generated from the types at definitely typed. This will need to be added there: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/firefox-webext-browser/index.d.ts#L378
> 
> PR: [DefinitelyTyped/DefinitelyTyped#64355](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64355)

@tm1000 Super thanks for taking this up. However, according to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64355, it does not seem to be a quick fix. Do you know anybody is taking this up in the upstream mozilla? Is it an option to have a local fix here in this repo?

**Comment by here-nerd** [comment]
You're totally right about the split mode on Mozilla. [It's simply not supported on Mozilla.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) Anyway, I still think Mozilla should have exposed generic types rather than exposing only its supported keys.

I want to help. I need a hint from you @tm1000 how [manifest.schema.json](https://github.com/webextension-toolbox/webpack-webextension-plugin/blob/main/src/plugin/manifest.schema.json) is currently created. E.g. why can't we just simply add 'split' in the schema? 
Anyway, there is also https://json.schemastore.org/chrome-manifest, which has the correct incognito key definition. How can we use that instead of the mozilla one?

**Comment by tm1000** [comment]
It's actually generated by this https://github.com/webextension-toolbox/webpack-webextension-plugin/blob/ed2c8d6a39813163dfa368ac1a0ac60b04559b95/package.json#L30

Which turns the typescript into json. I'm not opposed to using the chrome one. It should just be a simple file replace

**Comment by tm1000** [comment]
@here-nerd Here's a PR that I think will solve all of this: https://github.com/webextension-toolbox/webpack-webextension-plugin/pull/376

I also added tests
